language: node_js
node_js:
- lts/*
sudo: false
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: TbRl22Lxf1RZMlLS3BOGTUPj9PHNJQIMdPqF0m1p2TxHHCjhzppefbFXgBX/EckxLGwhLkB88G936HjzQ6c7vEQlRFrrNaMVAtsYw4s/vnpT0ldAuur3HcJvizL4l0setyHdc9jBqPV7eXm4p5N6Ojq9P6W3+bsyvV0cK1BYE1s=
  on:
    tags: true
    repo: noflo/noflo-runtime-base
  skip_cleanup: true
addons:
  chrome: stable
